name: Executar Cypress Diariamente

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:14.4.1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: cypress run

      - name: Instalar zip no container
        run: apt-get update && apt-get install -y zip

      - name: Compactar relatório
        run: |
          zip -r report.zip cypress/reports

      - name: Enviar Relatório por E-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Resultado dos Testes Cypress"
          to: marcos.ribeiro@prognum.com.br
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Olá!

            Segue o relatório dos testes Cypress executados.

            Atenciosamente,
            GitHub Actions
          # attachments removido para evitar bloqueio
          # attachments: report.zip
