name: Executar Cypress Diariamente

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:14.4.1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: cypress run

      - name: Listar arquivos no diretório de relatórios
        run: |
          echo "Arquivos gerados em cypress/reports:"
          find cypress/reports -type f

      - name: Verificar se o relatório existe
        run: |
          if [ ! -f cypress/reports/html/index.html ]; then
            echo "Relatório não encontrado!"
            exit 1
          else
            echo "Relatório encontrado."
          fi

      - name: Instalar rclone
        run: |
          apt-get update && apt-get install -y unzip
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          cp rclone-*-linux-amd64/rclone /usr/bin/rclone
          chmod +x /usr/bin/rclone
          rclone version

      - name: Configurar rclone
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS_JSON }}" > creds.json
          rclone config create gdrive drive scope=drive file_creds=creds.json --non-interactive

      - name: Fazer upload do relatório para o Google Drive
        run: |
          rclone copy cypress/reports/html/index.html gdrive:RelatoriosCypress

      - name: Enviar e-mail com link do relatório
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Resultado dos Testes Cypress"
          to: marcos.ribeiro@prognum.com.br
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Olá!

            Os testes Cypress foram executados com sucesso.

            ✅ O relatório está disponível no link abaixo:
            https://drive.google.com/drive/folders/<ID-DA-PASTA>

            Atenciosamente,
            GitHub Actions
